#!/usr/bin/env bash
# This script audits DNS records for a domain's subdomains.

get_dns_record() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print}')
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
    domain="$1"
    subdomain="$2"
    
    if [ -z "$subdomain" ]; then
        # If subdomain is not provided, check default subdomains
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            get_dns_record "$domain" "$sub"
        done
    else
        get_dns_record "$domain" "$subdomain"
    fi
}

main "$@"

