#!/usr/bin/env bash
# Display a list of currently running processes with user-oriented format and process hierarchy
printf "%-10s %-8s %-8s %-8s %-8s %-8s %-10s %-10s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "COMMAND"
ps aux --forest | awk '{printf "%-10s %-8s %-8s %-8s %-8s %-8s %-10s %-10s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $NF}'

