#!/usr/bin/env bash
# This script tells a story about each user in /etc/passwd
while IFS=: read -r username _ userid groupid _ homedir shell; do
    userinfo=$(getent passwd "$username" | cut -d ':' -f 5)
    password=$(getent passwd "$username" | cut -d ':' -f 2)
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd

