#!/bin/bash

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming traffic on specific TCP ports
sudo ufw allow 22/tcp     # Allow SSH
sudo ufw allow 443/tcp    # Allow HTTPS (SSL)
sudo ufw allow 80/tcp     # Allow HTTP

sudo ufw enable

