#!/usr/bin/env bash
# Server configuration script
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/^127\.0\.0\.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a ~/hosts.new > /dev/null
sudo cp -f ~/hosts.new /etc/hosts
echo "Configuration complete. Please revert /etc/hosts back to its original state after testing."

